#%RAML 1.0
title: Example
/example:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message" : "Oauth policy successfully applied"
              }