#%RAML 1.0
title: POC5-RAML
mediaType: application/json

/input:
  put:
    body:
      application/json:
        
    responses:
      200:
        body:
          application/json:
            
            example: !include /Example/example.raml
              