#%RAML 1.0 NamedExample
gl_Account_Response_Example:
  [
    {
        "Limestone_GL_account__c": "502005.0",
        "Description__c": "Auto Vac",
        "Type__c": "EE",
        "CLH_GL_Description__c": "UNUSED",
        "Id": null,
        "LAN_GL_Account__c": "UNUSED",
        "type": "Gl__c",
        "Earnings_Code__c": "CVAU",
        "Levels__c": "Direct - Variable Lvl 1",
        "Limestone_GL_account_Description__c": "Wages - Base pay - Variable"
    },
    {
        "Limestone_GL_account__c": "531005.0",
        "Description__c": "Auto Vac",
        "Type__c": "EE",
        "CLH_GL_Description__c": "UNUSED",
        "Id": null,
        "LAN_GL_Account__c": "UNUSED",
        "type": "Gl__c",
        "Earnings_Code__c": "CVAU",
        "Levels__c": "Direct - Fixed Lvl 1",
        "Limestone_GL_account_Description__c": "Wages - Base pay - Fixed"
    }
  ]