#%RAML 1.0 NamedExample
gl_Account_Request_Example:
 [
{
  "GLCode": "531005",
  "GLCodeType": "EE",
  "GL/PayAccountCode": "CVAU",
  "FinancialLevelDescription": "Direct-FixedLvl1"
},
{
  "GLCode": "502005",
  "GLCodeType": "EE",
  "GL/PayAccountCode": "CBRV",
  "FinancialLevelDescription": "Corp/Global-Lvl5 & 6"
}
]
