#%RAML 1.0
title: Task1_system
/flights:
      get:
        queryParameters:
          destination:
            required: false
            type: string
        responses:
          200:
            body:
              application/json:
                example: !include /Example/example.raml