#%RAML 1.0 Library
usage:
types:
  getProperties:
    properties:
      "GLCode": 
        required: true
        type: number
      "GL/PayAccountCode": 
         required: true
         type: string
      "GLCodeType":
        required: true
        type: string
      "FinancialLevelDescription":
       required: true
       type: string      
    