#%RAML 1.0
title: Proc
/proc:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"Sucess"
              }
      400:
        body:
          application/json:
            example:
              {
                "message": "BadRequest"
              }
