#%RAML 1.0
title: POC3-RAML
/flights:
      get:
        queryParameters:
          price:
            required: false
            type: number
        responses:
          200:
            body:
              application/json:
                example: !include /Example/poc3-example.raml
